/**
 * Application entry point.
 * Mounts the React root and registers the PWA service worker for offline caching.
 */
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

// Register the PWA service worker (generated by vite-plugin-pwa)
// This caches the app shell so the IDE loads offline after first visit.
import { registerSW } from "virtual:pwa-register";

const updateSW = registerSW({
  onNeedRefresh() {
    // In production, show a toast: "New version available. Refresh?"
    if (confirm("A new version of the IDE is available. Reload now?")) {
      updateSW(true);
    }
  },
  onOfflineReady() {
    console.log("[PWA] App shell cached — offline ready.");
  },
});

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
